from dataclasses import dataclass


@dataclass
class config:
    """
    Properties
    ----------
    rotate_to_sun_earth_plane: str=True
        If `True` all coordinates are rotated to the earth-sun plane's
        coordinate system.
        The data generated by the astropy-package is rotated approx. 23.45°
        around the x-axis compared to the orbital plane of most planets
        (including the earth).
    """
    rotate_to_sun_earth_plane: str=True
